services:
  - type: web
    name: jeffersondplay
    env: docker
    repo: https://github.com/josieljefferson/jeffersondplay
    branch: main
    plan: free
    autoDeploy: true
    healthCheckPath: /api/get.php?username=josielluz&password=3264717
